// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxuNflN-tUP5cHWg39y5wPXW6C9v2bLh4',
    appId: '1:247608885092:web:f481278c55c1a51332c471',
    messagingSenderId: '247608885092',
    projectId: 'bites-cacc7',
    authDomain: 'bites-cacc7.firebaseapp.com',
    storageBucket: 'bites-cacc7.firebasestorage.app',
    measurementId: 'G-01DDR8NQEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRhHORkqAr5TrmBuqUqGvaZMVjayc5xQE',
    appId: '1:247608885092:android:de521def91da0e9a32c471',
    messagingSenderId: '247608885092',
    projectId: 'bites-cacc7',
    storageBucket: 'bites-cacc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSraj1ZGGRB5QMJX3gOqJtB-h4rCFmQY',
    appId: '1:247608885092:ios:6f52dcd8d588cbd632c471',
    messagingSenderId: '247608885092',
    projectId: 'bites-cacc7',
    storageBucket: 'bites-cacc7.firebasestorage.app',
    iosBundleId: 'com.example.bites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWSraj1ZGGRB5QMJX3gOqJtB-h4rCFmQY',
    appId: '1:247608885092:ios:6f52dcd8d588cbd632c471',
    messagingSenderId: '247608885092',
    projectId: 'bites-cacc7',
    storageBucket: 'bites-cacc7.firebasestorage.app',
    iosBundleId: 'com.example.bites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxuNflN-tUP5cHWg39y5wPXW6C9v2bLh4',
    appId: '1:247608885092:web:55cbded31f3d777332c471',
    messagingSenderId: '247608885092',
    projectId: 'bites-cacc7',
    authDomain: 'bites-cacc7.firebaseapp.com',
    storageBucket: 'bites-cacc7.firebasestorage.app',
    measurementId: 'G-K9MK50MY40',
  );
}
